import { useEffect, useMemo, useState } from "react";
import { generateSkilltrackInsight, getAiStatus, isAiConfigured } from "../services/aiService";

const starterPromptsByRole = {
  student: [
    "What should I learn next?",
    "Analyze my skill gaps",
    "Build me a learning plan",
    "Which jobs match my skills?",
    "Explain my weakest skill",
  ],
  employer: [
    "Which candidates best fit this role?",
    "Compare the strongest applicants",
    "Explain the skill gap for this job",
    "What skills should we require?",
    "Summarize applicant fit",
  ],
  admin: [
    "Where are the biggest workforce gaps?",
    "Which skills are rising in demand?",
    "How ready is the workforce?",
    "Summarize employment trends",
    "What should we focus on next?",
  ],
};

function SkillTrackAI({
  role = "student",
  profile,
  skillProgress = [],
  attempts = [],
  learningProgress = [],
  pageContext = "",
  hideHeader = false,
}) {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [configured, setConfigured] = useState(isAiConfigured());

  useEffect(() => {
    let mounted = true;

    getAiStatus().then((status) => {
      if (mounted) {
        setConfigured(Boolean(status.configured));
      }
    }).catch(() => {
      if (mounted) setConfigured(false);
    });

    return () => {
      mounted = false;
    };
  }, []);

  const prompts = useMemo(() => starterPromptsByRole[role] || starterPromptsByRole.student, [role]);
  const contextualPlaceholder = {
    student: "What should I learn next?",
    employer: "Find candidates with strong JavaScript and React skills",
    admin: "Where are the biggest workforce skill gaps?",
  }[role] || "What should I learn next?";

  const submitPrompt = async (promptText) => {
    const text = (promptText || input || "").trim();

    if (!text) {
      setError("Enter a question or choose a suggested prompt.");
      return;
    }

    setLoading(true);
    setError("");
    setMessages((previous) => [
      ...previous,
      { id: Date.now(), sender: "user", text },
    ]);

    try {
      const result = await generateSkilltrackInsight({
        role,
        profile,
        prompt: text,
        skillProgress,
        attempts,
        learningProgress,
        pageContext: pageContext || `${role} workspace`,
      });

      setMessages((previous) => [
        ...previous,
        { id: Date.now() + 1, sender: "assistant", text: result.answer },
      ]);
      setInput("");
    } catch (requestError) {
      const message = requestError.message || "SkillTrack AI is temporarily unavailable.";
      setMessages((previous) => [
        ...previous,
        { id: Date.now() + 2, sender: "assistant", text: message },
      ]);
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  const clearConversation = () => {
    setMessages([]);
    setError("");
  };

  const handleKeyDown = (event) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      void submitPrompt();
    }
  };

  return (
    <section className={`panel ai-panel${hideHeader ? " ai-panel-embedded" : ""}`} aria-live="polite">
      {!hideHeader && (
        <div className="panel-header">
          <div>
            <p className="eyebrow">SKILLTRACK AI</p>
            <h2>{role === "employer" ? "Hiring guidance" : role === "admin" ? "Workforce intelligence" : "Your learning & career copilot"}</h2>
          </div>
          <span>{configured ? "Live AI" : "Guided Insight Mode"}</span>
        </div>
      )}

      {!configured && (
        <div className="data-warning">
          Guided Insight Mode is active. SkillTrack is using your live data to suggest the next action, but it is not generated by a real AI model because no provider is configured.
        </div>
      )}

      {error && (
        <div className="data-error">
          <span>{error}</span>
          <button type="button" className="button button-secondary" onClick={() => setError("")}>
            Retry
          </button>
        </div>
      )}

      <div className="ai-prompt-grid">
        <div className="ai-suggestions">
          {prompts.map((prompt) => (
            <button key={prompt} type="button" className="ai-suggestion" onClick={() => submitPrompt(prompt)}>
              {prompt}
            </button>
          ))}
        </div>

        <div className="ai-chat" role="log" aria-label="SkillTrack AI conversation">
          {messages.length === 0 ? (
            <div className="ai-empty-state">
              {role === "employer"
                ? "Ask SkillTrack AI for candidate fit, risk assessment, or hiring priorities."
                : role === "admin"
                  ? "Ask SkillTrack AI about workforce gaps, demand, readiness, and labour trends."
                  : "Ask SkillTrack AI about your next learning move, skill gaps, or job-readiness next step."}
            </div>
          ) : (
            messages.map((message) => (
              <div key={message.id} className={`ai-message ${message.sender}`}>
                <strong>{message.sender === "assistant" ? "SkillTrack AI" : "You"}</strong>
                <p>{message.text}</p>
              </div>
            ))
          )}
          {loading && <div className="ai-message assistant"><strong>SkillTrack AI</strong><p>Thinking...</p></div>}
        </div>
      </div>

      <div className="ai-input-row">
        <label htmlFor="skilltrack-ai-input" className="sr-only">
          Ask SkillTrack AI
        </label>
        <input
          id="skilltrack-ai-input"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={contextualPlaceholder}
          aria-label="Ask SkillTrack AI"
          disabled={loading}
        />
        <button type="button" className="button button-primary" onClick={() => submitPrompt()} disabled={loading}>
          {loading ? "Thinking..." : "Send"}
        </button>
        <button type="button" className="button button-secondary" onClick={clearConversation}>
          Clear
        </button>
      </div>
    </section>
  );
}

export default SkillTrackAI;
