import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { AppTable, PageHeader, PlatformLayout, StatCard, StatusBadge } from "../components/Platform";
import { getApplications, getJobMatches } from "../services/skilltrackService";
import { useAuth } from "../context/AuthContext";

function StudentApplicationTimeline({ status }) {
  const stages = status === "Rejected" ? ["Applied", "Under Review", "Rejected"] : ["Applied", "Under Review", "Shortlisted", "Interview", "Selected"];
  const currentIndex = stages.indexOf(status);
  return <div className="application-timeline">{stages.map((stage, index) => <div className={`timeline-step ${index <= currentIndex ? "complete" : ""} ${stage === status ? "current" : ""}`} key={stage}><span>{stage === "Rejected" ? "!" : index <= currentIndex ? "✓" : "○"}</span><strong>{stage}</strong>{index < stages.length - 1 && <i />}</div>)}</div>;
}

export function StudentApplicationDetails() {
  const { id } = useParams(); const { user } = useAuth(); const [state, setState] = useState({ loading: true, error: "", application: null, match: null });
  useEffect(() => { Promise.all([getApplications(user.id), getJobMatches(user.id)]).then(([applications, matches]) => { const application = applications.find((item) => item.id === id); setState({ loading: false, error: application ? "" : "Application not found.", application, match: matches.find((item) => item.id === application?.job_id) || null }); }).catch((error) => setState({ loading: false, error: error.message || "Unable to load application.", application: null, match: null })); }, [id, user.id]);
  if (state.loading) return <PlatformLayout><div className="route-state">Loading application details...</div></PlatformLayout>;
  if (state.error || !state.application) return <PlatformLayout><div className="data-error">{state.error || "Application not found."}</div></PlatformLayout>;
  const { application, match } = state;
  return <PlatformLayout><PageHeader eyebrow="APPLICATION DETAILS" title={application.jobs?.title || "Application"} description={`${application.jobs?.company_name || ""} · ${application.jobs?.location || ""}`} action={<StatusBadge>{application.status}</StatusBadge>} /><section className="job-detail-grid"><article className="panel job-detail-main"><h2>Application status</h2><StudentApplicationTimeline status={application.status} /><h2>Job information</h2><p>{application.jobs?.description || "No description provided."}</p><h2>Required skills</h2><div className="job-skills">{application.jobs?.job_skills?.map((skill) => <span key={skill.skill_id}>{skill.skills?.name} · minimum {skill.minimum_score}%</span>)}</div><h2>Your match</h2><div className="job-match-large"><strong>{match?.match ?? 0}%</strong><div><StatusBadge>{match?.matchLabel || "Low Match"}</StatusBadge><p>Calculated from your current skill progress.</p></div></div><div className="match-columns"><div><h3>Matched skills</h3>{match?.matchedSkills?.map((skill) => <p key={skill.skill_id}>{skill.skills?.name} · {skill.current}%</p>) || <p>None</p>}</div><div><h3>Missing skills</h3>{match?.missingSkills?.map((skill) => <p key={skill.skill_id}>{skill.skills?.name} · {skill.current === null ? "Not assessed" : `${skill.current}%`}</p>) || <p>None</p>}</div></div></article><aside className="panel job-apply-panel"><span className="section-kicker">APPLICATION STATUS</span><h2>{application.status}</h2><p>Applied {new Date(application.applied_at).toLocaleDateString()}</p><Link className="back-link" to="/applications">Back to applications</Link></aside></section></PlatformLayout>;
}

export default function Applications() {
  const { user } = useAuth();
  const [applications, setApplications] = useState([]);
  const [matches, setMatches] = useState({});
  const [state, setState] = useState({ loading: true, error: "" });
  useEffect(() => { Promise.all([getApplications(user.id), getJobMatches(user.id)]).then(([items, jobs]) => { setApplications(items); setMatches(Object.fromEntries(jobs.map((job) => [job.id, job]))); }).catch((error) => setState({ loading: false, error: error.message || "Unable to load applications." })).finally(() => setState((prev) => ({ ...prev, loading: false }))); }, [user.id]);
  return <PlatformLayout><PageHeader eyebrow="EMPLOYMENT TRACKING" title="Application tracker" description="Keep every opportunity, conversation, and next step in view." action={<Link className="button button-primary" to="/jobs">Find opportunities</Link>} /><section className="overview-grid three"><StatCard label="Active applications" value={applications.length} detail="From your database record" /><StatCard label="Interview pipeline" value={applications.filter((item) => item.status === "Interview").length} detail="Current interview stage" tone="green" /><StatCard label="Selected" value={applications.filter((item) => item.status === "Selected").length} detail="Employment outcomes" tone="orange" /></section><section className="panel panel-table"><div className="panel-header"><div><p className="eyebrow">YOUR PIPELINE</p><h2>Applied jobs</h2></div><span className="muted">Updated today</span></div>{state.loading && <div className="route-state">Loading your applications...</div>}{state.error && <div className="data-error">{state.error}</div>}{!state.loading && !state.error && !applications.length && <div className="empty-state">You haven't applied to any jobs yet.<br /><Link className="button button-primary" to="/jobs">Explore Jobs</Link></div>}{!state.loading && !state.error && applications.length > 0 && <AppTable headers={["Role", "Company", "Match", "Applied", "Status", "View"]} rows={applications.map((application) => <tr key={application.id}><td><strong>{application.jobs?.title}</strong></td><td>{application.jobs?.company_name}</td><td>{matches[application.job_id] ? `${matches[application.job_id].match}%` : "-"}</td><td>{new Date(application.applied_at).toLocaleDateString()}</td><td><StatusBadge>{application.status}</StatusBadge></td><td><Link className="table-action" to={`/applications/${application.id}`}>View application</Link></td></tr>)} />}</section></PlatformLayout>;
}
