import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AppTable, PageHeader, PlatformLayout, StatCard, StatusBadge } from "../components/Platform";
import { getApplications, getJobMatches } from "../services/skilltrackService";
import { useAuth } from "../context/AuthContext";

export default function Applications() {
  const { user } = useAuth();
  const [applications, setApplications] = useState([]);
  const [matches, setMatches] = useState({});
  const [state, setState] = useState({ loading: true, error: "" });
  useEffect(() => { Promise.all([getApplications(user.id), getJobMatches(user.id)]).then(([items, jobs]) => { setApplications(items); setMatches(Object.fromEntries(jobs.map((job) => [job.id, job]))); }).catch((error) => setState({ loading: false, error: error.message || "Unable to load applications." })).finally(() => setState((prev) => ({ ...prev, loading: false }))); }, [user.id]);
  return <PlatformLayout><PageHeader eyebrow="EMPLOYMENT TRACKING" title="Application tracker" description="Keep every opportunity, conversation, and next step in view." action={<Link className="button button-primary" to="/jobs">Find opportunities</Link>} /><section className="overview-grid three"><StatCard label="Active applications" value={applications.length} detail="From your database record" /><StatCard label="Interview pipeline" value={applications.filter((item) => item.status === "Interview").length} detail="Current interview stage" tone="green" /><StatCard label="Selected" value={applications.filter((item) => item.status === "Selected").length} detail="Employment outcomes" tone="orange" /></section><section className="panel panel-table"><div className="panel-header"><div><p className="eyebrow">YOUR PIPELINE</p><h2>Applied jobs</h2></div><span className="muted">Updated today</span></div>{state.loading && <div className="route-state">Loading your applications...</div>}{state.error && <div className="data-error">{state.error}</div>}{!state.loading && !state.error && !applications.length && <div className="empty-state">You haven't applied to any jobs yet.<br /><Link className="button button-primary" to="/jobs">Explore Jobs</Link></div>}{!state.loading && !state.error && applications.length > 0 && <AppTable headers={["Role", "Company", "Match", "Applied", "Status", "View"]} rows={applications.map((application) => <tr key={application.id}><td><strong>{application.jobs?.title}</strong></td><td>{application.jobs?.company_name}</td><td>{matches[application.job_id] ? `${matches[application.job_id].match}%` : "-"}</td><td>{new Date(application.applied_at).toLocaleDateString()}</td><td><StatusBadge>{application.status}</StatusBadge></td><td><Link className="table-action" to={`/jobs/${application.job_id}`}>View job</Link></td></tr>)} />}</section></PlatformLayout>;
}
