import { useState } from "react";
import { Link, useNavigate, useParams, useLocation } from "react-router-dom";
import { assessmentQuestions } from "../data/mockData";
import { PageHeader, PlatformLayout, ProgressBar } from "../components/Platform";

function ResultView() {
  const navigate = useNavigate();
  const score = 70;
  return <PlatformLayout><PageHeader eyebrow="ASSESSMENT COMPLETE" title="JavaScript assessment results" description="Your result has been added to your skill profile." action={<span className="status-badge passed">Result saved</span>} /><section className="result-hero"><div className="score-ring"><strong>{score}%</strong><span>Score</span></div><div><p className="eyebrow">PERFORMANCE</p><h2>Good progress, with room to grow</h2><p>You answered 7 of 10 questions correctly and reached an Intermediate level.</p></div><div className="result-stats"><span>Correct answers<strong>7 / 10</strong></span><span>Skill level<strong>Intermediate</strong></span></div></section><div className="result-grid"><section className="panel"><div className="panel-header"><h2>Skill-gap analysis</h2><span>Target: 80%</span></div><div className="gap-meter"><div><span>JavaScript</span><strong>Current 70%</strong></div><ProgressBar value={70} /><div className="target-line" style={{ left: "80%" }} /></div><div className="result-columns"><div><h3>Strong areas</h3><ul className="check-list"><li>Variables and functions</li><li>Arrays and objects</li><li>ES6 syntax</li></ul></div><div><h3>Skill gaps</h3><ul className="gap-check-list"><li>Async JavaScript</li><li>Promises and API handling</li><li>DOM manipulation</li></ul></div></div></section><section className="panel recommendation-panel"><p className="eyebrow">RECOMMENDED ACTION</p><h2>Close your JavaScript gap</h2><p>Complete the focused module, then retake this assessment to measure improvement.</p><button className="button button-primary full-width" onClick={() => navigate("/learning")}>Improve skills</button><button className="button button-secondary full-width" onClick={() => navigate("/assessments/javascript")}>Retake assessment</button></section></div><Link className="back-link" to="/dashboard">Back to dashboard</Link></PlatformLayout>;
}

export default function AssessmentFlow() {
  const { id } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const isResult = location.pathname.endsWith("/results");
  const [started, setStarted] = useState(false);
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState({});
  if (isResult) return <ResultView />;
  const question = assessmentQuestions[current];
  const selectAnswer = (index) => setAnswers((prev) => ({ ...prev, [question.id]: index }));
  return <PlatformLayout><PageHeader eyebrow="SKILL ASSESSMENT" title={started ? "JavaScript Logic Test" : "Assess your JavaScript skills"} description={started ? "Answer each question based on your current understanding." : "A 10-question diagnostic assessment designed to identify your next best learning actions."} />{!started ? <section className="assessment-intro panel"><div className="assessment-icon">JS</div><div><span className="level-badge">Intermediate · 10 questions · 12 minutes</span><h2>Measure what you know today</h2><p>This assessment covers variables, functions, arrays, asynchronous JavaScript, the DOM, and modern language features. You can review answers before submitting.</p><ul className="check-list"><li>One correct answer per question</li><li>Navigate freely between questions</li><li>Results include a personalised skill-gap report</li></ul><button className="button button-primary" onClick={() => setStarted(true)}>Start assessment</button></div></section> : <section className="assessment-workspace"><div className="assessment-progress"><div><strong>Question {current + 1} of {assessmentQuestions.length}</strong><span>{Math.round(((current + 1) / assessmentQuestions.length) * 100)}% complete</span></div><ProgressBar value={((current + 1) / assessmentQuestions.length) * 100} /></div><div className="question-layout"><aside className="question-nav"><h3>Questions</h3><div>{assessmentQuestions.map((item, index) => <button key={item.id} className={`${index === current ? "current" : ""} ${answers[item.id] !== undefined ? "answered" : ""}`} onClick={() => setCurrent(index)}>{index + 1}</button>)}</div><p>{Object.keys(answers).length} answered</p></aside><div className="question-card panel"><span className="question-category">{question.category}</span><h2>{question.text}</h2><div className="options">{question.options.map((option, index) => <button key={option} className={answers[question.id] === index ? "selected" : ""} onClick={() => selectAnswer(index)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div><div className="question-actions"><button className="button button-secondary" disabled={current === 0} onClick={() => setCurrent(current - 1)}>Previous</button>{current === assessmentQuestions.length - 1 ? <button className="button button-primary" onClick={() => navigate(`/assessments/${id || "javascript"}/results`)}>Submit assessment</button> : <button className="button button-primary" onClick={() => setCurrent(current + 1)}>Next question</button>}</div></div></div></section>}</PlatformLayout>;
}
