import { Link } from "react-router-dom";
import { candidateMatches, jobs, assessments } from "../data/mockData";
import { AppTable, PageHeader, PlatformLayout, ProgressBar, StatCard, StatusBadge } from "../components/Platform";

const analytics = [{ label: "JavaScript", value: 42 }, { label: "Data Structures", value: 36 }, { label: "React", value: 29 }, { label: "Communication", value: 24 }, { label: "SQL", value: 19 }];

export function AdminDashboard() {
  return <PlatformLayout role="admin"><PageHeader eyebrow="NATIONAL SKILLS INTELLIGENCE" title="Programme overview" description="Monitor candidate readiness, demand, and employment outcomes across SkillTrack." action={<button className="button button-primary">Export report</button>} /><section className="overview-grid admin-kpis"><StatCard label="Total candidates" value="12,480" detail="+8.4% this quarter" /><StatCard label="Assessments completed" value="8,920" detail="71% completion rate" tone="green" /><StatCard label="Average skill score" value="71%" detail="+4 pts this quarter" tone="orange" /><StatCard label="Active opportunities" value="1,240" detail="186 added this month" tone="navy" /><StatCard label="Placements" value="3,482" detail="27% conversion rate" tone="green" /></section><div className="admin-grid"><section className="panel analytics-panel"><div className="panel-header"><div><p className="eyebrow">SKILL GAP ANALYTICS</p><h2>Where support is needed</h2></div><span>Last 30 days</span></div>{analytics.map((item) => <div className="analytics-row" key={item.label}><div><strong>{item.label}</strong><span>{item.value}% gap</span></div><ProgressBar value={item.value} tone={item.value > 35 ? "orange" : "blue"} /></div>)}</section><section className="panel employment-panel"><div className="panel-header"><div><p className="eyebrow">EMPLOYMENT OUTCOMES</p><h2>Placement trend</h2></div><span className="trend">+18%</span></div><div className="bar-chart">{[42, 55, 48, 68, 62, 82, 74, 92].map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /><small>{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"][index]}</small></div>)}</div></section></div><section className="panel panel-table"><div className="panel-header"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Assessment activity</h2></div><Link className="table-action" to="/admin/assessments">View all</Link></div><AppTable headers={["Assessment", "Skill", "Score", "Status"]} rows={assessments.slice(0, 4).map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.skill}</td><td><strong>{item.score}%</strong></td><td><StatusBadge>{item.status}</StatusBadge></td></tr>)} /></section></PlatformLayout>;
}

export function EmployerDashboard() {
  return <PlatformLayout role="employer"><PageHeader eyebrow="EMPLOYER CONSOLE" title="Build your next team" description="Reach assessed candidates whose skills align with your open roles." action={<button className="button button-primary">+ Post a job</button>} /><section className="overview-grid three"><StatCard label="Active jobs" value="08" detail="2 closing this week" /><StatCard label="New applications" value="124" detail="+24 since Monday" tone="green" /><StatCard label="Candidate matches" value="36" detail="92% average match" tone="orange" /></section><section className="panel panel-table employer-table"><div className="panel-header"><div><p className="eyebrow">CANDIDATE MATCHING</p><h2>Recommended candidates</h2></div><span>For: Frontend Developer</span></div><AppTable headers={["Candidate", "Skill match", "Experience", "Assessment", "Status"]} rows={candidateMatches.map((candidate) => <tr key={candidate.name}><td><strong>{candidate.name}</strong></td><td><span className="match-pill">{candidate.match}%</span></td><td>{candidate.experience}</td><td>{candidate.score}%</td><td><StatusBadge>{candidate.status}</StatusBadge></td></tr>)} /></section><div className="section-title"><div><p className="eyebrow">OPEN ROLES</p><h2>Active job opportunities</h2></div><Link className="table-action" to="/employer/jobs">Manage jobs</Link></div><section className="resource-grid employer-jobs">{jobs.slice(0, 3).map((job) => <article className="job-card" key={job.id}><div className="job-header-row"><div><h3>{job.title}</h3><p>{job.company} · {job.location}</p></div><span className="match-pill">{job.match}% fit</span></div><p className="muted">{job.skills.join(" · ")}</p><button className="button button-secondary full-width">View applicants</button></article>)}</section></PlatformLayout>;
}
