-- SkillTrack database schema. Run in Supabase SQL editor or migration tooling.
create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('student', 'employer', 'admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.job_status as enum ('Draft', 'Active', 'Closed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.application_status as enum ('Applied', 'Shortlisted', 'Interview', 'Selected', 'Rejected'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', email text not null default '', role public.user_role not null default 'student',
  phone text, location text, education text, career_goal text, bio text, profile_completion integer not null default 0 check (profile_completion between 0 and 100),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.skills (id bigint generated by default as identity primary key, name text not null unique, category text, description text, target_score integer not null default 80 check (target_score between 0 and 100), created_at timestamptz not null default now());
create table if not exists public.questions (id bigint generated by default as identity primary key, skill_id bigint not null references public.skills(id) on delete cascade, question_text text not null, option_a text not null, option_b text not null, option_c text not null, option_d text not null, correct_option smallint not null check (correct_option between 0 and 3), topic text not null, difficulty text not null default 'Intermediate', created_at timestamptz not null default now());
create table if not exists public.assessments (id bigint generated by default as identity primary key, skill_id bigint not null references public.skills(id) on delete cascade, title text not null, description text, duration_minutes integer not null default 12, question_count integer not null default 10, created_at timestamptz not null default now());
create table if not exists public.assessment_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, assessment_id bigint not null references public.assessments(id) on delete cascade, score numeric not null default 0, total_questions integer not null, correct_answers integer not null, percentage integer not null check (percentage between 0 and 100), performance_level text not null, started_at timestamptz, completed_at timestamptz not null default now());
create table if not exists public.assessment_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.assessment_attempts(id) on delete cascade, question_id bigint not null references public.questions(id) on delete cascade, selected_option smallint check (selected_option between 0 and 3), is_correct boolean not null default false, created_at timestamptz not null default now(), unique (attempt_id, question_id));
create table if not exists public.skill_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, skill_id bigint not null references public.skills(id) on delete cascade, current_score integer not null default 0 check (current_score between 0 and 100), target_score integer not null default 80 check (target_score between 0 and 100), gap_percentage integer not null default 80, last_assessed_at timestamptz, updated_at timestamptz not null default now(), unique (user_id, skill_id));
create table if not exists public.learning_resources (id bigint generated by default as identity primary key, skill_id bigint not null references public.skills(id) on delete cascade, title text not null, description text, level text, estimated_minutes integer, resource_url text, created_at timestamptz not null default now());
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), employer_id uuid not null references public.profiles(id) on delete cascade, title text not null, company_name text not null, location text, description text, experience_required text, employment_type text, salary_range text, status public.job_status not null default 'Draft', created_at timestamptz not null default now());
create table if not exists public.job_skills (id bigint generated by default as identity primary key, job_id uuid not null references public.jobs(id) on delete cascade, skill_id bigint not null references public.skills(id) on delete cascade, minimum_score integer not null default 60 check (minimum_score between 0 and 100), unique (job_id, skill_id));
create table if not exists public.applications (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, status public.application_status not null default 'Applied', applied_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (job_id, user_id));
create table if not exists public.certifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, skill_id bigint not null references public.skills(id) on delete cascade, name text not null, score integer not null check (score between 0 and 100), issued_at timestamptz not null default now(), certificate_number text not null unique, status text not null default 'Verified');

create or replace function public.profile_completion_value(p public.profiles) returns integer language sql immutable as $$ select round((array_length(array_remove(array[p.full_name, p.phone, p.location, p.education, p.career_goal, p.bio], null), 1)::numeric / 6) * 100)::integer $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, email) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), new.email) on conflict (id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

alter table public.profiles enable row level security; alter table public.skills enable row level security; alter table public.questions enable row level security; alter table public.assessments enable row level security; alter table public.assessment_attempts enable row level security; alter table public.assessment_answers enable row level security; alter table public.skill_progress enable row level security; alter table public.learning_resources enable row level security; alter table public.jobs enable row level security; alter table public.job_skills enable row level security; alter table public.applications enable row level security; alter table public.certifications enable row level security;

create policy profiles_self on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy profiles_update_self on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy profiles_admin_all on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy skills_read_authenticated on public.skills for select using (auth.uid() is not null);
create policy skills_admin_manage on public.skills for all using (public.is_admin()) with check (public.is_admin());
create policy questions_read_authenticated on public.questions for select using (auth.uid() is not null);
create policy questions_admin_manage on public.questions for all using (public.is_admin()) with check (public.is_admin());
create policy assessments_read_authenticated on public.assessments for select using (auth.uid() is not null);
create policy assessments_admin_manage on public.assessments for all using (public.is_admin()) with check (public.is_admin());
create policy attempts_self on public.assessment_attempts for select using (user_id = auth.uid() or public.is_admin());
create policy attempts_insert_self on public.assessment_attempts for insert with check (user_id = auth.uid());
create policy attempts_admin on public.assessment_attempts for all using (public.is_admin()) with check (public.is_admin());
create policy answers_self on public.assessment_answers for select using (exists (select 1 from public.assessment_attempts a where a.id = attempt_id and a.user_id = auth.uid()) or public.is_admin());
create policy answers_insert_self on public.assessment_answers for insert with check (exists (select 1 from public.assessment_attempts a where a.id = attempt_id and a.user_id = auth.uid()));
create policy answers_admin on public.assessment_answers for all using (public.is_admin()) with check (public.is_admin());
create policy progress_self on public.skill_progress for select using (user_id = auth.uid() or public.is_admin());
create policy progress_insert_self on public.skill_progress for insert with check (user_id = auth.uid());
create policy progress_update_self on public.skill_progress for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy progress_admin on public.skill_progress for all using (public.is_admin()) with check (public.is_admin());
create policy resources_read_authenticated on public.learning_resources for select using (auth.uid() is not null);
create policy resources_admin on public.learning_resources for all using (public.is_admin()) with check (public.is_admin());
create policy jobs_read_active on public.jobs for select using (status = 'Active' or employer_id = auth.uid() or public.is_admin());
create policy jobs_employer_manage on public.jobs for all using (employer_id = auth.uid() or public.is_admin()) with check (employer_id = auth.uid() or public.is_admin());
create policy job_skills_read_authenticated on public.job_skills for select using (auth.uid() is not null);
create policy job_skills_employer_manage on public.job_skills for all using (exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid()) or public.is_admin()) with check (exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid()) or public.is_admin());
create policy applications_student_own on public.applications for select using (user_id = auth.uid() or public.is_admin() or exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid()));
create policy applications_student_insert on public.applications for insert with check (user_id = auth.uid());
create policy applications_employer_update on public.applications for update using (exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid()) or public.is_admin()) with check (exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid()) or public.is_admin());
create policy applications_admin on public.applications for all using (public.is_admin()) with check (public.is_admin());
create policy certifications_self on public.certifications for select using (user_id = auth.uid() or public.is_admin());
create policy certifications_admin on public.certifications for all using (public.is_admin()) with check (public.is_admin());
create index if not exists questions_skill_id_idx on public.questions(skill_id); create index if not exists attempts_user_id_idx on public.assessment_attempts(user_id); create index if not exists applications_user_id_idx on public.applications(user_id); create index if not exists jobs_employer_id_idx on public.jobs(employer_id);
